name: Java CI/CD with Maven

# Controls when the workflow will run
on:
    # Triggers the workflow on push events but only for the master branch
    push:
        branches: [ master, develop ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
        inputs:
            version:
                description: 'Image version'
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout the repo
                uses: actions/checkout@v3

            -   name: Set up JDK 11
                uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'temurin'
                    cache: maven

            -   name: Maven settings
                uses: s4u/maven-settings-action@v2.8.0
                with:
                    servers: '[{"id": "github", "username": "${USERNAME}", "password": "${ACCESS_TOKEN}"}]'
                    githubServer: false

            -   name: Build with Maven
                run: mvn clean package
                env:
                    USERNAME: ${{ secrets.USERNAME }}
                    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
